# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:



  ########################################################################################################################
  #
  #   Github Actions dependencies
  #
  ########################################################################################################################
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    labels:
      - "GHA dependency"
