name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-composer:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: QA - Run composer validate
        uses: docker://jakzal/phpqa:php7.4-alpine
        with:
          args: composer validate --strict --no-check-lock --ansi
      - name: QA - Run composer normalize
        uses: docker://jakzal/phpqa:php7.4-alpine
        with:
          args: composer normalize --dry-run

  code-style-check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        php:
          - '7.4'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: memory_limit=-1
          tools: php-cs-fixer
          coverage: none
      - name: Run PHP-CS-Fixer fix
        run: php-cs-fixer fix --dry-run --diff --ansi

  phpunit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.4'
          - 'rc'
        include:
          - php: '7.4'
            coverage: false
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: setup-php
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v1
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ansi
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --colors=always
